#pragma once
#include "../../IRUM_util/IRUM_Common.h"

#define STRAT_OPEN			"STRAT_OPEN"
#define STRATID_NONE		"STRAT_NONE"
#define STRATID_BUY_OPEN	"STRAT_BUY_OPEN"
#define STRATID_SELL_OPEN	"STRAT_SELL_OPEN"
#define STRATID_SELL_SL		"STRAT_SELL_SL"
#define STRATID_SELL_PT		"STRAT_SELL_PT"
#define STRATID_SELL_PSECURED	"STRAT_SELL_PSECURED"
#define STRATID_BUY_SL			"STRAT_BUY_SL"
#define STRATID_BUY_PT			"STRAT_BUY_PT"
#define STRATID_BUY_PSECURED	"STRAT_BUY_PSECURED"
#define STRATID_MARKET_CLR		"STRAT_MARKET_CLR"

