//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by XingAPI_Sample.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_XINGAPTYPE                  129
#define IDD_LOGIN                       130
#define IDD_t1101                       131
#define IDD_TR_BAR                      132
#define IDD_t1301                       133
#define IDD_t5511                       134
#define IDD_FC0                         135
#define IDD_t0431                       136
#define IDD_t0433                       137
#define IDD_t6024                       138
#define IDD_t6011                       139
#define IDD_SC0                         140
#define IDD_SC1                         141
#define IDD_SC2                         142
#define IDD_SC3                         143
#define IDD_SC4                         144
#define IDD_SC_                         145
#define IDD_s2_ELW                      146
#define IDD_IJ_                         147
#define IDD_YJ_                         148
#define IDD_PM_                         149
#define IDD_KM_                         150
#define IDD_BM_                         151
#define IDD_BMT                         152
#define IDD_NWS                         153
#define IDD_S3_                         154
#define IDD_S4_                         155
#define IDD_H1_                         156
#define IDD_H2_                         157
#define IDD_YS3                         158
#define IDD_KS_                         159
#define IDD_K3_                         160
#define IDD_HA_                         161
#define IDD_HB_                         162
#define IDD_YK3                         163
#define IDD_s3_ELW                      164
#define IDD_s4_ELW                      165
#define IDD_h3_ELW                      166
#define IDD_h2_ELW                      167
#define IDD_TH_                         168
#define IDD_TS_                         169
#define IDD_FH0                         170
#define IDD_OC0                         171
#define IDD_OH0                         172
#define IDD_NWS1                        173
#define IDD_JIF                         174
#define IDD_O01                         175
#define IDD_H01                         176
#define IDD_C01                         177
#define IDD_t9907                       178
#define IDD_DIALOG1                     179
#define IDD_DIALOG2                     180
#define IDD_t9905                       181
#define IDD_t2101                       182
#define IDC_CURSOR1                     183
#define IDD_FC1                         183
#define IDD_FC0_1                       183
#define IDC_TREE_TR                     1000
#define IDC_EDIT_INBLOCK_SHCODE         1000
#define IDC_COMBO_TR                    1001
#define IDC_BUTTON_REQUEST              1001
#define IDC_BUTTON_SEARCH               1002
#define IDC_LIST_OUTBLOCK               1002
#define IDC_LIST_OUTBLOCK1              1003
#define IDC_BUTTON_REQUEST_H            1003
#define IDC_EDIT_INBLOCK_CVOLUME        1004
#define IDC_LIST_OUTBLOCK2              1004
#define IDC_RADIO_REAL                  1005
#define IDC_EDIT_INBLOCK_STARTTIME      1005
#define IDC_LIST_OUTBLOCK3              1005
#define IDC_RADIO_SIMUL                 1006
#define IDC_EDIT_INBLOCK_ENDTIME        1006
#define IDC_BUTTON_INBLOCK2_ADD         1006
#define IDC_EDIT_ID                     1007
#define IDC_BUTTON_REQUEST_NEXT         1007
#define IDC_COMBO_INBLOCK_MEMEGB        1007
#define IDC_CHECK_SAVE_ID               1008
#define IDC_EDIT_INBLOCK_CTS_TIME       1008
#define IDC_BUTTON_INBLOCK2_DEL         1008
#define IDC_EDIT_PWD                    1009
#define IDC_EDIT_INBLOCK_PRICE          1009
#define IDC_EDIT_CERT_PWD               1010
#define IDC_EDIT_INBLOCK_RECCNT         1010
#define IDC_COMBO_SERVER_ADDR_TYPE      1011
#define IDC_EDIT_SERVER_IP              1012
#define IDC_EDIT_INBLOCK_PASSWD         1012
#define IDC_COMBO_SERVER_PORT           1013
#define IDC_EDIT_INBLOCK_EXPCODE        1013
#define IDC_EDIT_INBLOCK_ORDAMT         1013
#define IDC_BUTTON_LOGIN                1014
#define IDC_EDIT_INBLOCK_QTY            1014
#define IDC_EDIT_INBLOCK1_RECCNT2       1014
#define IDC_CHECK_SEND_PACKET_SIZE      1015
#define IDC_EDIT_CODE                   1015
#define IDC_EDIT_INBLOCK2_FOCODENO      1015
#define IDC_COMBO_SEND_PACKET_SIZE      1016
#define IDC_EDIT_INBLOCK2_PRICE         1016
#define IDC_EDIT_CODE_H                 1016
#define IDC_CHECK_CONNECT_TIMEOUT       1017
#define IDC_EDIT_INBLOCK_CTS_EXPCODE    1017
#define IDC_EDIT_INBLOCK2_ORDQTY        1017
#define IDC_EDIT_CONNECT_TIMEOUT        1018
#define IDC_EDIT_INBLOCK_CTS_MEDOCD     1018
#define IDC_CHECK_SHOW_CERT_ERR_DLG     1019
#define IDC_EDIT_INBLOCK_KWBPNO         1021
#define IDC_EDIT_INBLOCK_JANGB          1022
#define IDC_LIST_t9907                  1024
#define IDC_EDIT_INBLOCK_TONGSINGB      1025
#define IDC_LIST_t9905                  1026
#define IDC_EDIT_INBLOCK_LOANDT         1027
#define IDC_EDIT_INBLOCK_MEMNUMBER      1028
#define IDC_LIST_OUTBLOCK_H             1028
#define IDC_LIST1                       1029
#define IDC_LIST_SISEHOGA               1029
#define IDC_EDIT_INBLOCK_STRAGB         1030
#define IDC_BUTTON1                     1030
#define IDC_EDIT_INBLOCK_GROUPID        1031
#define IDC_BUTTON_UNADVISE             1031
#define IDC_EDIT_INBLOCK_ORDERNUM       1032
#define IDC_LIST2                       1032
#define IDC_LIST_REAL                   1032
#define IDC_LIST_RESULT                 1032
#define IDC_EDIT_INBLOCK_PORTNUM        1033
#define IDC_LIST_TR                     1033
#define IDC_COMBO_INBLOCK_HOGAGB        1034
#define IDC_BUTTON_TEST                 1034
#define IDC_COMBO_INBLOCK_PGMTYPE       1035
#define IDC_BUTTON_END                  1035
#define IDC_COMBO_INBLOCK_GONGTYPE      1036
#define IDC_COMBO_INBLOCK_GONGHOGA      1037
#define IDC_COMBO_INBLOCK_SINMEMECODE   1039
#define IDC_COMBO_INBLOCK_ORDCONDGB     1040
#define IDC_COMBO_INBLOCK_OPPBUYGB      1042
#define IDC_EDIT_INBLOCK_BASKETNUM      1043
#define IDC_EDIT_INBLOCK_TRANCHNUM      1044
#define IDC_EDIT_INBLOCK_ITEMNUM        1045
#define IDC_EDIT_INBLOCK_OPERORDNUM     1046
#define IDC_COMBO_INBLOCK_FLOWSUPGB     1048
#define IDC_COMBO_INBLOCK_ACCNO         1049
#define IDC_COMBO_INBLOCK_GUBUN         1050
#define IDC_COMBO_INBLOCK_FOHOGAGB      1051
#define IDC_COMBO_INBLOCK2_MEMEGB       1052

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
